# Random Forest Classification

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
tf.__version__
# from google.colab import drive
# drive.mount('/content/drive')

'2.3.0'

## Importing the dataset

In [ ]:
dataset = pd.read_csv('Final_trial_dataset.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
dataset.isnull().sum().sum()
# dataset1 = pd.read_csv('/content/drive/My Drive/Subject107_cleaned.csv')
# X_test_extra = dataset1.iloc[:, 2:].values
# y_test_extra = dataset1.iloc[:, 1].values
# dataset2 = pd.read_csv('/content/drive/My Drive/Subject108_cleaned.csv')
# X_test_extra2 = dataset2.iloc[:, 1:].values
# y_test_extra2 = dataset2.iloc[:, 0].values
# print(dataset1.isnull().sum().sum())
# print(y_test_extra)
count = dataset.groupby(['Activity']).count() 
print(count) 
# print(y_test_extra2)
dataset.head()
print(dataset.Activity.unique())
print(y)

          tGravityAcc-mean()-X  ...  tBodyGyro-mean()-Z
Activity                        ...                    
1                         1286  ...                1286
2                         1374  ...                1374
3                         1407  ...                1407
4                         1226  ...                1226
5                          986  ...                 986
6                         1073  ...                1073

[6 rows x 6 columns]
[2 1 3 4 5 6]
[2 2 2 ... 6 6 6]


In [ ]:
x = dataset[['acc_x']].values.astype(float)

# Create a minimum and maximum processor object
min_max_scaler = preprocessing.MinMaxScaler()

# Create an object to transform the data to fit minmax processor
x_scaled = min_max_scaler.fit_transform(x)

# Run the normalizer on the dataframe
df_normalized = pd.DataFrame(x_scaled)
df_normalized

NameError: ignored

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:-1])
X[:, 1:-1] = imputer.transform(X[:, 1:-1])
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.10, random_state = 0)
# X_val, X_test, y_val, y_test = train_test_split(X_test, y_test, test_size = 0.5, random_state = 0)
print(X_train,y_train)

[[ 0.9682011  -0.16005285 -0.02665421  0.07165225 -0.13577764  0.03166798]
 [ 0.84719542 -0.38432218 -0.23932957  0.02902002 -0.09795775  0.02897086]
 [ 0.97526869 -0.06670305  0.07908569 -0.02349958 -0.00743339  0.07488092]
 ...
 [ 0.8467426   0.27673906  0.251297   -0.27051525 -0.42653266 -0.58075153]
 [-0.27677871  0.88945577  0.41099081 -0.02682406 -0.07892687  0.08971353]
 [ 0.83629162  0.33297663 -0.19058824 -0.03720267  0.001761    0.19679061]] [4 4 2 ... 1 3 1]


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)

X_test = sc.transform(X_test)
# X_test_extra2 = sc.transform(X_test_extra2)
# X_test_extra= sc.transform(X_test_extra)


## Training the Random Forest Classification model on the Training set

In [ ]:
# y_train = tf.keras.utils.to_categorical(

#     y_train,

#     num_classes=None,

#     dtype='float32'

# )

# y_test = tf.keras.utils.to_categorical(

#     y_test,

#     num_classes=None,

#     dtype='float32'

# )

In [ ]:


cnn = tf.keras.models.Sequential()

cnn.add(tf.keras.layers.Dense(units=8, activation='relu'))
cnn.add(tf.keras.layers.Dense(units=10, activation='relu'))

cnn.add(tf.keras.layers.Dense(units=8, activation='relu'))
cnn.add(tf.keras.layers.Dense(units=15, activation='relu'))
cnn.add(tf.keras.layers.Dense(units=16, activation='relu'))
cnn.add(tf.keras.layers.Dense(units=14, activation='relu'))

cnn.add(tf.keras.layers.Dense(units= 10, activation='softmax'))

cnn.compile(optimizer='rmsprop', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
# earlystopping = callbacks.EarlyStopping(monitor ="categorical_crossentropy",  
#                                         mode ="auto", patience = 5,  
#                                         restore_best_weights = True)

cnn.fit(X_train, y_train, batch_size = 32, epochs = 500)


Epoch 1/500
207/207 [==============================] - 1s 3ms/step - loss: 1.7511 - accuracy: 0.2715
Epoch 2/500
207/207 [==============================] - 1s 3ms/step - loss: 1.2021 - accuracy: 0.4586
Epoch 3/500
207/207 [==============================] - 1s 3ms/step - loss: 1.0772 - accuracy: 0.4992
Epoch 4/500
207/207 [==============================] - 1s 3ms/step - loss: 1.0204 - accuracy: 0.5453
Epoch 5/500
207/207 [==============================] - 1s 3ms/step - loss: 0.9843 - accuracy: 0.5565
Epoch 6/500
207/207 [==============================] - 1s 3ms/step - loss: 0.9657 - accuracy: 0.5668
Epoch 7/500
207/207 [==============================] - 1s 3ms/step - loss: 0.9524 - accuracy: 0.5745
Epoch 8/500
207/207 [==============================] - 1s 3ms/step - loss: 0.9346 - accuracy: 0.5787
Epoch 9/500
207/207 [==============================] - 1s 3ms/step - loss: 0.9109 - accuracy: 0.5874
Epoch 10/500
207/207 [==============================] - 1s 3ms/step - loss: 0.8858 - accura

In [ ]:
y_pred = cnn.predict(X_test)
# y_pred2=cnn.predict(X_test_extra)
# y_pred3=cnn.predict(X_test_extra2)
y_pred = (y_pred > 0.30)
# y_pred2 = (y_pred2 > 0.5)
# y_pred3 = (y_pred3 > 0.5)
y_pred=np.argmax(y_pred, axis=1)
# y_pred2=np.argmax(y_pred2, axis=1)
# y_pred3=np.argmax(y_pred3,axis=1)
from sklearn.metrics import confusion_matrix, accuracy_score
# print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
# from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm," first_answer")
print(accuracy_score(y_test, y_pred)," first accuracy")
# # cm1 = confusion_matrix(y_test_extra, y_pred2)
# print(cm1," second_answer")
# print(accuracy_score(y_test_extra, y_pred2)," real accuracy one")
# cm2 = confusion_matrix(y_test_extra2, y_pred3)
# print(cm2," third_answer")
# print(accuracy_score(y_test_extra2, y_pred3)," real accuracy two")

[[  0   0   0   0   0   0   0]
 [  0 133   6   0   1   1   0]
 [  1  23  88   0  25   0   1]
 [  0   0   0 136   0   0   1]
 [  0   4  30   0  66  10  10]
 [  0   2   2   0  22  50  16]
 [  0   0   1   0  11  24  72]]  first_answer
0.7404891304347826  first accuracy


In [ ]:
print(y_pred)

[3 2 6 2 3 5 3 1 5 4 4 1 1 5 4 6 5 2 1 3 2 6 2 4 1 2 4 3 2 1 3 1 5 4 1 6 4
 3 6 6 2 1 2 1 1 2 2 6 1 3 3 6 5 4 2 1 1 3 5 1 1 1 6 4 2 2 5 4 5 1 1 2 1 6
 2 5 2 5 2 2 3 1 1 1 4 1 5 1 1 3 1 1 2 1 2 5 2 6 5 5 1 6 3 3 6 4 3 1 5 5 2
 1 4 6 1 4 2 5 1 2 2 2 1 6 2 6 4 4 1 5 2 3 6 1 3 4 4 3 4 4 6 5 4 1 3 1 4 3
 3 4 4 1 3 5 3 1 5 1 1 6 6 2 3 1 4 1 1 2 2 6 3 4 1 3 6 5 6 3 1 1 1 6 4 6 6
 4 2 2 3 2 4 1 3 2 3 3 6 6 3 2 6 4 4 4 6 1 5 4 6 6 1 6 2 3 6 1 2 6 6 2 4 4
 3 5 5 3 4 1 1 1 3 1 1 1 1 3 3 4 5 1 4 1 2 5 5 5 4 5 2 2 5 5 5 2 1 3 3 5 4
 3 4 3 4 2 4 3 4 1 6 4 2 4 1 4 3 4 4 4 4 5 5 6 5 1 1 3 4 2 1 4 2 2 6 4 3 1
 3 4 4 6 3 1 4 6 1 3 2 2 6 3 4 3 2 4 1 6 2 2 4 3 1 1 6 4 4 4 6 6 1 3 3 6 1
 1 5 3 4 2 3 6 3 3 6 3 5 3 4 1 1 3 5 1 1 4 3 5 4 3 1 1 2 1 3 2 2 3 2 3 3 4
 1 4 6 2 4 4 6 6 3 6 2 1 6 3 6 6 1 6 3 3 5 6 1 3 5 1 3 3 2 2 4 2 6 1 4 3 3
 4 6 4 1 3 1 2 1 5 4 1 2 1 5 4 1 1 3 4 4 2 3 3 3 2 3 5 1 4 1 4 6 3 5 2 4 5
 5 2 3 5 2 4 4 6 1 6 5 5 6 1 2 3 2 4 6 3 1 6 1 2 2 3 1 1 1 6 2 3 6 5 4 5 1
 4 4 2 5 1 3 5 5 2 5 3 6 

In [ ]:
loss, acc = cnn.evaluate(X_test, y_test)

23/23 [==============================] - 0s 1ms/step - loss: 0.6954 - accuracy: 0.7024


**Actual Test Accuracy**

In [ ]:
# print(loss, acc)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 50, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=50,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [ ]:
def classify(pulserate,bodytemp,accx,accy,accz,gyrox,gyroy,gyroz):
  x=(cnn.predict(sc.transform([[pulserate,bodytemp,accx,accy,accz,gyrox,gyroy,gyroz]])))
  y_value=(x>0.5)
  y_final=np.argmax(y_value,axis=1)
  return y_final

## Predicting a new result

In [ ]:
# print(cnn.predict(([[105,36,-8.43,5.8,-0.35,0.006,0.03,0.02]])))
y_pred = cnn.predict(([[72,36.1,-9.6,7.2,0.9,-0.006,0.03,-0.02]]))
# y_pred = cnn.predict(sc.transform([[72,0.35,7.2,0.9,-0.006,0.03,-0.02]]))
y_pred = (y_pred > 0.35)
y_pred=np.argmax(y_pred, axis=1)
print(y_pred)
# keras_file = 'hackmodel_1.h5'
# cnn.save(keras_file)
# import tensorflow as tf
# keras_model = tf.keras.models.load_model('/content/hackmodel_1.h5')
# converter = tf.lite.TFLiteConverter.from_keras_model(keras_model)
# tflite_model = converter.convert()
# file = open( 'finalmit1.tflite' , 'wb' )
# file.write(tflite_model)

[2]


## Making the Confusion Matrix and Predicting the Test set results

In [ ]:
y_pred = classifier.predict(X_test)
# y_pred_2=classifier.predict(X_test_extra)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)
# cm1 = confusion_matrix(y_test_extra, y_pred_2)
# print(cm1)
# accuracy_score(y_test_extra, y_pred_2)

[[3 3]
 [2 2]
 [6 5]
 ...
 [1 1]
 [4 4]
 [1 1]]
[[134   5   0   2   0   0]
 [  3 118   0  16   1   0]
 [  0   0 137   0   0   0]
 [  1   8   0 101   7   3]
 [  2   0   0  19  58  13]
 [  0   3   0   7   6  92]]


0.8695652173913043

In [ ]:
import matplotlib.pyplot as plt 

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('InceptionV3 Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['train', 'validation'], loc='lower right')
plt.show()

In [ ]:
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('InceptionV3 loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'validation'], loc='upper right')
plt.show()

In [ ]:
print(cnn.predict(X_test))

In [ ]:
# interpreter = tf.lite.Interpreter(model_path='finalmit1.tflite')
# # OR interpreter = tf.lite.Interpreter(model_content=tflite_model)
# interpreter.allocate_tensors()
# input_details = interpreter.get_input_details()
# output_details = interpreter.get_output_details()
# print(output_details)

In [ ]:
# import pickle
# pickle.dump(cnn, open('model.pkl','wb'))

# model = pickle.load(open('model.pkl','rb'))
# print(model.predict(sc.transform([[72,36.1,-9.6,7.2,0.9,-0.006,0.03,-0.02]])))
classifier.save("finalgun113.h5")


AttributeError: ignored